sonar.projectName=RVC_OOAD
sonar.sourceEncoding=UTF-8

sonar.sources=src,include,apps,simulator,system_tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*.cpp,tests/**/*.cc,tests/**/*.cxx

sonar.exclusions=build/**,coverage/**,.github/**,tests/**/_deps/**
sonar.coverage.exclusions=tests/**,include/**,apps/**,simulator/**,system_tests/**

sonar.cfamily.compile-commands=build/compile_commands.json
sonar.coverageReportPaths=coverage/sonarqube.xml
